@startuml
title Diagrama de seqüència - Registrar-se

actor "Usuari no registrat" as Usuari

participant "GestorUsuaris\n:Control" as Gestor
participant "Usuari\n:Entitat" as UsuariDB

Usuari -> Gestor: omplirFormulari()
activate Gestor

Gestor -> UsuariDB: verificarExistencia()
activate UsuariDB
UsuariDB --> Gestor: existeix
deactivate UsuariDB

alt existeix == false
    Gestor -> Gestor: xifrarContrasenya()
    Gestor -> UsuariDB: crearCompte()
    activate UsuariDB
    UsuariDB --> Gestor: compteCreat
    deactivate UsuariDB
    Gestor --> Usuari: confirmacioRegistre()
else existeix == true
    Gestor --> Usuari: error()
end

deactivate Gestor
@enduml
