@startuml
title Diagrama de seqüència - Reservar comanda (cuiner no disponible)

actor Client

boundary "PantallaReserva" as Pantalla
control "GestorComandes" as Gestor
entity "Cuiner" as CuinerDB
entity "Comanda" as ComandaDB

Client -> Pantalla: seleccionarCuinerNoDisponible()
activate Pantalla

Pantalla -> Gestor: sollicitarReserva()
activate Gestor

Gestor -> CuinerDB: obtenirHoraDisponibilitat()
activate CuinerDB
CuinerDB --> Gestor: horaRetorn
deactivate CuinerDB

Gestor --> Pantalla: mostrarHoraDisponible()
Pantalla --> Client: informarHora()

Client -> Pantalla: confirmarReserva()
Pantalla -> Gestor: crearReserva()

Gestor -> ComandaDB: insertarReserva()
activate ComandaDB
ComandaDB --> Gestor: reservaConfirmada
deactivate ComandaDB

Gestor --> Pantalla: confirmacioReserva()
Pantalla --> Client: reservaConfirmada()

deactivate Gestor
deactivate Pantalla
@enduml
