@startuml
skinparam defaultFontName Helvetica

title Diagrama de sequencia - Subscriure's a un pla mensual

actor Client
boundary "PantallaSubscripcio" as Pantalla
control "GestorSubscripcions" as Gestor
entity "ClientRegistrat" as ClientEntitat
entity "Subscripcio" as SubscripcioEntitat

Client -> Pantalla: accedirSubscripcio()
Pantalla -> Gestor: consultarPlaMensual()
Gestor -> SubscripcioEntitat: obtenirInformacioPla()
SubscripcioEntitat --> Gestor: informacioPla
Gestor --> Pantalla: mostrarPlaMensual()
Pantalla --> Client: mostraInformacioPla()

Client -> Pantalla: confirmarSubscripcio()
Pantalla -> Gestor: sollicitarSubscripcio()
Gestor -> ClientEntitat: comprovarSubscripcio()
ClientEntitat --> Gestor: estatSubscripcio

alt client no subscrit
    Gestor -> SubscripcioEntitat: registrarSubscripcio()
    SubscripcioEntitat --> Gestor: subscripcioCreada
    Gestor -> ClientEntitat: associarSubscripcio()
    ClientEntitat --> Gestor: subscripcioAssociada
    Gestor --> Pantalla: subscripcioConfirmada()
    Pantalla --> Client: mostraConfirmacio()
else client ja subscrit
    Gestor --> Pantalla: informarSubscripcioActiva()
    Pantalla --> Client: mostraMissatge()
end

@enduml

