@startuml DiagramUnamed-veure-plats-cuiners
title DS - Veure plats/menus o cuiners actius

actor Client as Cl
participant "Sistema QueMenges" as S

Cl -> S: obrir catalog
S -> S: filtrar cuiners actius i plats
S --> Cl: mostrar llistat

@enduml
