@startuml
title Diagrama de seqüència - Veure les meves valoracions

actor Client

boundary "PantallaValoracions" as Pantalla
control "GestorValoracions" as Gestor
entity "Valoracio" as ValoracioDB

Client -> Pantalla: obrirValoracions()
activate Pantalla

Pantalla -> Gestor: sollicitarValoracions()
activate Gestor

Gestor -> ValoracioDB: obtenirValoracionsClient()
activate ValoracioDB
ValoracioDB --> Gestor: llistatValoracions
deactivate ValoracioDB

alt existeixenValoracions
    Gestor --> Pantalla: retornarValoracions()
    Pantalla --> Client: mostrarLlistat()
else noHiHaValoracions
    Gestor --> Pantalla: informarSenseValoracions()
    Pantalla --> Client: mostrarMissatgeInformatiu()
end

deactivate Gestor
deactivate Pantalla
@enduml
