@startuml us-client-01-consulta
skinparam actorStyle awesome
left to right direction

title Client — Exploració

actor Client

usecase "Veure plats/menús o cuiners actius" as UC1
usecase "Veure resultats ordenats per distància" as UC2
usecase "Veure tots els plats d'un cuiner" as UC3
usecase "Reservar comanda per quan el cuiner estigui disponible" as UC4

Client --> UC1
Client --> UC2
Client --> UC3
Client --> UC4

@enduml
