@startuml us-cuiner-01-disponibilitat-recollida
skinparam actorStyle awesome
left to right direction

title Cuiner — Disponibilitat i recollida

actor Cuiner

usecase "Indicar disponibilitat\ni hora de comandes" as UC1
usecase "Definir com es pot recollir\n(repartidor / cuiner / client)" as UC2

Cuiner --> UC1
Cuiner --> UC2

@enduml
