@startuml
title Diagrama de seqüència - Realitzar lliurament de comanda

actor Repartidor
actor Client

participant "GestorComandes\n:Control" as Gestor
participant "Comanda\n:Entitat" as ComandaDB

Repartidor -> Gestor: seleccionarComanda()
activate Gestor

Gestor -> ComandaDB: obtenirEstat()
activate ComandaDB
ComandaDB --> Gestor: estat = "recollida"
deactivate ComandaDB

Repartidor -> Gestor: confirmarLliurament()
Gestor -> ComandaDB: actualitzarEstat()
activate ComandaDB
ComandaDB --> Gestor: estatActualitzat
deactivate ComandaDB

Gestor -> Client: notificarComandaRebuda()
Gestor --> Repartidor: confirmacioLliurament()

deactivate Gestor
@enduml
