@startuml us-overview-repartidor
skinparam actorStyle stickman
left to right direction

title Cas d'ús — repartidor

actor "Repartidor" as actorRepartidor
actor "Mapa" as Mapa
actor "Passarel·la de pagament" as Pay

rectangle "QueMenges" {
  usecase "Visualitzar comandes d'enviament" as R0
  usecase "Realitzar lliurament de comanda" as R1
  usecase "Proporcionar ubicació GPS" as R2
  usecase "Rebre ingrés per enviament" as R3
}

actorRepartidor --> R0
actorRepartidor --> R1
actorRepartidor --> R2
actorRepartidor --> R3



R2 ..> Mapa
R3 ..> Pay

@enduml